### ISSUE TITLE
Document process for adding a package

### ISSUE THREAD

**Issue by jgabry** [stan-dev/r-packages#1]
Maybe in the readme file?

**Comment by rok-cesnovar** [comment]
Readme.md should have that yes. Though the readme is also where https://mc-stan.org/r-packages/ points now.

**Comment by rok-cesnovar** [comment]
Updated with instructions for stan-dev/r-packages maintainers and non-maintainers. Feel free to edit.

**Comment by jgabry** [comment]
Great, thanks!
