### ISSUE TITLE
Question: recommendations for working with old versions?

### ISSUE THREAD

**Issue by karldw** [stan-dev/r-packages#11]
First, let me say thanks for the great project!

**Issue**

I recently tried to re-initialize an older project that relied on cmdstanr 0.5.3. That version of cmdstanr was archived in b7fff8ebf6433a766cc62c3aef297d5e01f491c4 and is no longer listed as an available package in https://mc-stan.org/r-packages/src/contrib/PACKAGES. I can still install from the Github release tag [v0.5.3](https://github.com/stan-dev/cmdstanr/releases/tag/v0.5.3), but I was tripped up installing it with my existing code.

I ran into this issue using `remotes`, but I'm guessing `renv` would encounter similar issues.

```r
# Existing code that fails:
remotes::install_version(
  "cmdstanr", 
  "0.5.3", # would work with "0.6.0"
  dependencies=FALSE,
  upgrade="never",
  repos=c("https://mc-stan.org/r-packages", getOption("repos"))
)
#> Error in download_version_url(package, version, repos, type) : 
#>  version '0.5.3' is invalid for package 'cmdstanr'


# Works, but doesn't use mc-stan.org repo
remotes::install_github(
  "stan-dev/cmdstanr", ref="v0.5.3",
  dependencies=FALSE,
  upgrade="never"
)
```

**Question**
Were the versions before 0.6.0 removed intentionally? More generally, do you have recommendations for how should I be writing code that allows users in the future to replicate my `cmdstanr` environment?

**Comment by bob-carpenter** [comment]
Hi, @karldw.  You can find all of the releases of a GitHub package under the "Releases" list.  For cmdstanr, that's here:

https://github.com/stan-dev/cmdstanr/releases

I'm not an R expert and don't know remotes or renv.  If this answers your question, please close this issue.  

You can submit questions like this to our forums, which are read by a much larger group than our devs:  https://discourse.mc-stan.org

**Comment by karldw** [comment]
Thanks @bob-carpenter! Sorry for the slow reply.

I was wrong about renv. Even though the example I gave doesn't work, renv works fine.


```r
repos <- c(Stan = "https://mc-stan.org/r-packages/", CRAN = "https://cloud.r-project.org")
options(repos = repos)

# Note that this will make renv and .Rprofile changes, so best to run in a new, clean folder.
renv::init()
# restart R as directed

# This works:
renv::install("cmdstanr@0.5.3")

```

I appreciate your help here, and all the time you and the other developers spend building and maintaining these tools. I understand there are real challenges to getting cmdstanr on CRAN (e.g., https://github.com/stan-dev/cmdstanr/issues/590), but it would smooth out some of these installation speed bumps 

Thanks!
Karl

**Comment by bob-carpenter** [comment]
I don't see that the thread https://github.com/stan-dev/cmdstanr/issues/590 mentions any hurdles to getting cmdstanr on CRAN.  

The major problems I have with CRAN are:

* very small max package size (required RStan to be broken into several packages)
* lack of version dependency control (requires new packages to interoperate with new and old packages while propagating through the system---they used to give us a pass on this, but stopped doing that)
* third-party unit testing on any aspect of an API (there is no private methods/functions in R and people lock in tests on typos in error messages, for example)
* requiring compatibility with hardware unknown to anyone under the age of 40

All of these have combined in the perfect storm to put RStan where it is now and I would argue that like much of the R language itself, every one of these decisions is well intentioned but computationally misguided.
