### ISSUE TITLE
List StanHeaders

### ISSUE THREAD

**Issue by avehtari** [stan-dev/r-packages#6]
The repo readme and https://mc-stan.org/r-packages/ list `rstan` but should list also `StanHeaders` as the `rstan` in `r-packages` doesn't work with the CRAN version of the `StanHeaders'. I was first confused as `StanHeaders` is not listed, but eventually had the courage to try to install it from `r-packages` anyway and it did work and now the `rstan` with Stan 2.26 works, too. So this is just a request to list it.

**Comment by rok-cesnovar** [comment]
Thanks. Added.
